"""Authentication module for agency-quickdeploy.

Supports two authentication methods:
1. API Key (ANTHROPIC_API_KEY) - Usage-based billing
2. OAuth Token (CLAUDE_CODE_OAUTH_TOKEN) - Subscription-based billing

OAuth tokens are generated via `claude setup-token` and can be stored
either as an environment variable or in ~/.claude/.credentials.json.
"""
import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class AuthType(Enum):
    """Authentication type for Claude Code."""

    API_KEY = "api_key"
    OAUTH = "oauth"


# Token prefix patterns
API_KEY_PREFIX = "sk-ant-api"
OAUTH_TOKEN_PREFIX = "sk-ant-oat"


def validate_api_key(api_key: Optional[str]) -> bool:
    """Validate an Anthropic API key.

    Args:
        api_key: The API key to validate

    Returns:
        True if the key appears valid, False otherwise
    """
    if not api_key:
        return False
    return api_key.startswith(API_KEY_PREFIX)


def validate_oauth_token(token: Optional[str]) -> bool:
    """Validate a Claude Code OAuth token.

    Args:
        token: The OAuth token to validate

    Returns:
        True if the token appears valid, False otherwise
    """
    if not token:
        return False
    return token.startswith(OAUTH_TOKEN_PREFIX)


@dataclass
class OAuthCredentials:
    """OAuth credentials for Claude Code.

    These are typically stored in ~/.claude/.credentials.json
    and are generated by `claude setup-token`.
    """

    access_token: str
    refresh_token: Optional[str] = None
    expires_at: Optional[int] = None
    scopes: list[str] = field(default_factory=list)


def parse_oauth_credentials_json(json_str: str) -> Optional[OAuthCredentials]:
    """Parse OAuth credentials from JSON string.

    Args:
        json_str: JSON string containing credentials (from .credentials.json)

    Returns:
        OAuthCredentials if valid, None otherwise
    """
    try:
        data = json.loads(json_str)
    except (json.JSONDecodeError, TypeError):
        return None

    oauth_data = data.get("claudeAiOauth")
    if not oauth_data:
        return None

    access_token = oauth_data.get("accessToken")
    if not access_token:
        return None

    return OAuthCredentials(
        access_token=access_token,
        refresh_token=oauth_data.get("refreshToken"),
        expires_at=oauth_data.get("expiresAt"),
        scopes=oauth_data.get("scopes", []),
    )


def generate_credentials_json(creds: OAuthCredentials) -> str:
    """Generate credentials JSON string.

    Args:
        creds: OAuth credentials to serialize

    Returns:
        JSON string suitable for ~/.claude/.credentials.json
    """
    oauth_data = {"accessToken": creds.access_token}

    if creds.refresh_token:
        oauth_data["refreshToken"] = creds.refresh_token
    if creds.expires_at:
        oauth_data["expiresAt"] = creds.expires_at
    if creds.scopes:
        oauth_data["scopes"] = creds.scopes

    return json.dumps({"claudeAiOauth": oauth_data}, indent=2)


@dataclass
class Credentials:
    """Container for authentication credentials.

    Can hold either API key or OAuth credentials, but not both.
    Use the factory methods to create instances.
    """

    auth_type: AuthType
    api_key: Optional[str] = None
    oauth: Optional[OAuthCredentials] = None

    @classmethod
    def from_api_key(cls, api_key: str) -> "Credentials":
        """Create credentials from an API key.

        Args:
            api_key: Anthropic API key

        Returns:
            Credentials instance configured for API key auth
        """
        return cls(auth_type=AuthType.API_KEY, api_key=api_key)

    @classmethod
    def from_oauth(cls, oauth: OAuthCredentials) -> "Credentials":
        """Create credentials from OAuth tokens.

        Args:
            oauth: OAuth credentials

        Returns:
            Credentials instance configured for OAuth auth
        """
        return cls(auth_type=AuthType.OAUTH, oauth=oauth)

    @classmethod
    def from_oauth_json(cls, json_str: str) -> Optional["Credentials"]:
        """Create credentials from OAuth JSON string.

        Args:
            json_str: JSON string from .credentials.json

        Returns:
            Credentials instance or None if invalid
        """
        oauth = parse_oauth_credentials_json(json_str)
        if oauth:
            return cls.from_oauth(oauth)
        return None

    def get_vm_metadata(self) -> dict[str, str]:
        """Generate VM instance metadata for these credentials.

        Returns:
            Dict of metadata key-value pairs to pass to the VM
        """
        metadata = {"auth-type": self.auth_type.value}

        if self.auth_type == AuthType.API_KEY and self.api_key:
            metadata["anthropic-api-key"] = self.api_key
        elif self.auth_type == AuthType.OAUTH and self.oauth:
            metadata["oauth-credentials"] = generate_credentials_json(self.oauth)

        return metadata
